/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    users: User
    departments: Department
    'academic-council-members': AcademicCouncilMember
    'educational-programs': EducationalProgram
    'admission-campaigns': AdmissionCampaign
    'tuition-rates': TuitionRate
    'document-categories': DocumentCategory
    documents: Document
    media: Media
    'payload-kv': PayloadKv
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {}
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>
    'academic-council-members':
      | AcademicCouncilMembersSelect<false>
      | AcademicCouncilMembersSelect<true>
    'educational-programs': EducationalProgramsSelect<false> | EducationalProgramsSelect<true>
    'admission-campaigns': AdmissionCampaignsSelect<false> | AdmissionCampaignsSelect<true>
    'tuition-rates': TuitionRatesSelect<false> | TuitionRatesSelect<true>
    'document-categories': DocumentCategoriesSelect<false> | DocumentCategoriesSelect<true>
    documents: DocumentsSelect<false> | DocumentsSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: number
  }
  fallbackLocale: null
  globals: {
    'specializations-page-settings': SpecializationsPageSetting
    'tuition-page-settings': TuitionPageSetting
  }
  globalsSelect: {
    'specializations-page-settings':
      | SpecializationsPageSettingsSelect<false>
      | SpecializationsPageSettingsSelect<true>
    'tuition-page-settings': TuitionPageSettingsSelect<false> | TuitionPageSettingsSelect<true>
  }
  locale: null
  widgets: {
    collections: CollectionsWidget
  }
  user: User
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number
  name: string
  roles: ('admin' | 'editor')[]
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  sessions?:
    | {
        id: string
        createdAt?: string | null
        expiresAt: string
      }[]
    | null
  password?: string | null
  collection: 'users'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: number
  name: string
  shortName: string
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null
  slug: string
  description: string
  websiteUrl: string
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academic-council-members".
 */
export interface AcademicCouncilMember {
  id: number
  name: string
  councilRole: 'chair' | 'deputy-chair' | 'secretary' | 'member'
  sortOrder: number
  position: string
  description: string
  departments?: (number | Department)[] | null
  /**
   * Завантажте файл або вкажіть HTTPS-посилання нижче.
   */
  photo?: (number | null) | Media
  /**
   * Зовнішнє HTTPS-посилання. Залиште порожнім, якщо фото завантажене як файл.
   */
  photoUrl?: string | null
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number
  /**
   * Обов’язково заповнюй для зображень. Для PDF можна залишити порожнім.
   */
  alt?: string | null
  caption?: string | null
  blurDataURL?: string | null
  category: 'document' | 'page-image' | 'news' | 'gallery' | 'other'
  prefix?: string | null
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
  sizes?: {
    thumbnail?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    card?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    hero?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educational-programs".
 */
export interface EducationalProgram {
  id: number
  title: string
  shortTitle: string
  /**
   * Формується автоматично з назви програми, рівня освіти та кодів спеціальності.
   */
  adminTitle?: string | null
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null
  slug: string
  /**
   * Новий код, наприклад F2.
   */
  specialtyCode: string
  /**
   * Старий код, наприклад 121.
   */
  legacySpecialtyCode: string
  specialtyName: string
  educationLevel: 'bachelor' | 'master'
  department: number | Department
  studyForms: {
    form: 'full-time' | 'part-time'
    durationLabel: string
    note?: string | null
    id?: string | null
  }[]
  isFeatured?: boolean | null
  sortOrder?: number | null
  description: string
  heroText: string
  tags?:
    | {
        label: string
        id?: string | null
      }[]
    | null
  careers?:
    | {
        title: string
        description?: string | null
        id?: string | null
      }[]
    | null
  studyFocus?:
    | {
        title: string
        description?: string | null
        id?: string | null
      }[]
    | null
  faq?:
    | {
        question: string
        answer: string
        id?: string | null
      }[]
    | null
  seoTitle?: string | null
  seoDescription?: string | null
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admission-campaigns".
 */
export interface AdmissionCampaign {
  id: number
  /**
   * Формується автоматично з року, форми та освітньої програми.
   */
  adminTitle?: string | null
  educationalProgram: number | EducationalProgram
  campaignYear: number
  studyForm: 'full-time' | 'part-time'
  licensedCapacity?: number | null
  maxStateOrder?: number | null
  statisticsYear?: number | null
  averageBudgetScore?: number | null
  averageContractScore?: number | null
  statisticsUrl?: string | null
  dataUpdatedAt: string
  sortOrder?: number | null
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tuition-rates".
 */
export interface TuitionRate {
  id: number
  /**
   * Формується автоматично з року, форми та освітньої програми.
   */
  adminTitle?: string | null
  /**
   * Рівень освіти (бакалавр/магістр) береться з обраної освітньої програми.
   */
  educationalProgram: number | EducationalProgram
  academicYear: string
  studyForm: 'full-time' | 'part-time'
  availability: 'available' | 'unavailable' | 'to-be-announced'
  amountPerYear?: number | null
  totalAmount?: number | null
  currency: 'UAH'
  note?: string | null
  sortOrder?: number | null
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-categories".
 */
export interface DocumentCategory {
  id: number
  title: string
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null
  slug: string
  sortOrder?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number
  /**
   * Формується автоматично. Відредагуйте назву вручну за потреби; очистіть поле, щоб повернути автоматичний режим.
   */
  title: string
  generatedTitleSnapshot?: string | null
  documentType:
    | 'regulation'
    | 'order'
    | 'educational-program'
    | 'previous-educational-program'
    | 'syllabus'
    | 'work-program'
    | 'curriculum'
    | 'accreditation'
    | 'review'
    | 'other'
  documentDate?: string | null
  periodLabel?: string | null
  /**
   * Завантажте PDF. Можна одночасно вказати зовнішнє посилання.
   */
  file?: (number | null) | Media
  /**
   * Якщо також вибрано файл, на сайті пріоритет матиме завантажений файл.
   */
  externalUrl?: string | null
  description?: string | null
  /**
   * Документ відображатиметься на сторінках усіх вибраних програм.
   */
  educationalPrograms?: (number | EducationalProgram)[] | null
  showInRegulatoryCatalog?: boolean | null
  category?: (number | null) | DocumentCategory
  source?: ('faculty' | 'university') | null
  sortOrder?: number | null
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number
  document?:
    | ({
        relationTo: 'users'
        value: number | User
      } | null)
    | ({
        relationTo: 'departments'
        value: number | Department
      } | null)
    | ({
        relationTo: 'academic-council-members'
        value: number | AcademicCouncilMember
      } | null)
    | ({
        relationTo: 'educational-programs'
        value: number | EducationalProgram
      } | null)
    | ({
        relationTo: 'admission-campaigns'
        value: number | AdmissionCampaign
      } | null)
    | ({
        relationTo: 'tuition-rates'
        value: number | TuitionRate
      } | null)
    | ({
        relationTo: 'document-categories'
        value: number | DocumentCategory
      } | null)
    | ({
        relationTo: 'documents'
        value: number | Document
      } | null)
    | ({
        relationTo: 'media'
        value: number | Media
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: number | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number
  user: {
    relationTo: 'users'
    value: number | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T
  roles?: T
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
  sessions?:
    | T
    | {
        id?: T
        createdAt?: T
        expiresAt?: T
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  name?: T
  shortName?: T
  generateSlug?: T
  slug?: T
  description?: T
  websiteUrl?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academic-council-members_select".
 */
export interface AcademicCouncilMembersSelect<T extends boolean = true> {
  name?: T
  councilRole?: T
  sortOrder?: T
  position?: T
  description?: T
  departments?: T
  photo?: T
  photoUrl?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educational-programs_select".
 */
export interface EducationalProgramsSelect<T extends boolean = true> {
  title?: T
  shortTitle?: T
  adminTitle?: T
  generateSlug?: T
  slug?: T
  specialtyCode?: T
  legacySpecialtyCode?: T
  specialtyName?: T
  educationLevel?: T
  department?: T
  studyForms?:
    | T
    | {
        form?: T
        durationLabel?: T
        note?: T
        id?: T
      }
  isFeatured?: T
  sortOrder?: T
  description?: T
  heroText?: T
  tags?:
    | T
    | {
        label?: T
        id?: T
      }
  careers?:
    | T
    | {
        title?: T
        description?: T
        id?: T
      }
  studyFocus?:
    | T
    | {
        title?: T
        description?: T
        id?: T
      }
  faq?:
    | T
    | {
        question?: T
        answer?: T
        id?: T
      }
  seoTitle?: T
  seoDescription?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admission-campaigns_select".
 */
export interface AdmissionCampaignsSelect<T extends boolean = true> {
  adminTitle?: T
  educationalProgram?: T
  campaignYear?: T
  studyForm?: T
  licensedCapacity?: T
  maxStateOrder?: T
  statisticsYear?: T
  averageBudgetScore?: T
  averageContractScore?: T
  statisticsUrl?: T
  dataUpdatedAt?: T
  sortOrder?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tuition-rates_select".
 */
export interface TuitionRatesSelect<T extends boolean = true> {
  adminTitle?: T
  educationalProgram?: T
  academicYear?: T
  studyForm?: T
  availability?: T
  amountPerYear?: T
  totalAmount?: T
  currency?: T
  note?: T
  sortOrder?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-categories_select".
 */
export interface DocumentCategoriesSelect<T extends boolean = true> {
  title?: T
  generateSlug?: T
  slug?: T
  sortOrder?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T
  generatedTitleSnapshot?: T
  documentType?: T
  documentDate?: T
  periodLabel?: T
  file?: T
  externalUrl?: T
  description?: T
  educationalPrograms?: T
  showInRegulatoryCatalog?: T
  category?: T
  source?: T
  sortOrder?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T
  caption?: T
  blurDataURL?: T
  category?: T
  prefix?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
        card?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
        hero?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specializations-page-settings".
 */
export interface SpecializationsPageSetting {
  id: number
  /**
   * Цей рік використовується для вибору даних вступної кампанії.
   */
  activeAdmissionCampaignYear: number
  groups: {
    /**
     * Значення для навігаційного посилання без символу #.
     */
    anchor: string
    interestLabel: string
    title: string
    description: string
    specialtyCodes: {
      code: string
      id?: string | null
    }[]
    id?: string | null
  }[]
  /**
   * Порядок елементів визначає порядок карток на сторінці. У заголовку можна використати {year}.
   */
  applicantResources: {
    /**
     * Placeholder {year} буде замінено активним роком вступної кампанії.
     */
    title: string
    description: string
    destinationType: 'link' | 'file'
    /**
     * Внутрішній шлях з / або повне посилання з http:// чи https://.
     */
    href?: string | null
    /**
     * Завантажте новий PDF або виберіть наявний у Media.
     */
    file?: (number | null) | Media
    id?: string | null
  }[]
  _status?: ('draft' | 'published') | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tuition-page-settings".
 */
export interface TuitionPageSetting {
  id: number
  /**
   * Цей рік використовується для вибору тарифів на публічній сторінці.
   */
  activeAcademicYear: string
  officialDocumentTitle: string
  /**
   * Завантажте файл або вкажіть HTTPS-посилання нижче ("Посилання на документ" пріоритетніше).
   */
  officialDocumentFile?: (number | null) | Media
  /**
   * Зовнішнє HTTPS-посилання. Залиште порожнім, якщо документ завантажено як файл.
   */
  officialDocumentUrl?: string | null
  officialDocumentDate?: string | null
  recipientName: string
  recipientCode: string
  recipientBank: string
  iban: string
  /**
   * Залиште зрозумілі місця для ПІБ студента, курсу та факультету.
   */
  paymentPurposeTemplate: string
  paymentNote?: string | null
  _status?: ('draft' | 'published') | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specializations-page-settings_select".
 */
export interface SpecializationsPageSettingsSelect<T extends boolean = true> {
  activeAdmissionCampaignYear?: T
  groups?:
    | T
    | {
        anchor?: T
        interestLabel?: T
        title?: T
        description?: T
        specialtyCodes?:
          | T
          | {
              code?: T
              id?: T
            }
        id?: T
      }
  applicantResources?:
    | T
    | {
        title?: T
        description?: T
        destinationType?: T
        href?: T
        file?: T
        id?: T
      }
  _status?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tuition-page-settings_select".
 */
export interface TuitionPageSettingsSelect<T extends boolean = true> {
  activeAcademicYear?: T
  officialDocumentTitle?: T
  officialDocumentFile?: T
  officialDocumentUrl?: T
  officialDocumentDate?: T
  recipientName?: T
  recipientCode?: T
  recipientBank?: T
  iban?: T
  paymentPurposeTemplate?: T
  paymentNote?: T
  _status?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown
  }
  width: 'full'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
