/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    users: User
    departments: Department
    'educational-programs': EducationalProgram
    'tuition-rates': TuitionRate
    'program-documents': ProgramDocument
    'payload-kv': PayloadKv
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {}
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>
    'educational-programs': EducationalProgramsSelect<false> | EducationalProgramsSelect<true>
    'tuition-rates': TuitionRatesSelect<false> | TuitionRatesSelect<true>
    'program-documents': ProgramDocumentsSelect<false> | ProgramDocumentsSelect<true>
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: number
  }
  fallbackLocale: null
  globals: {}
  globalsSelect: {}
  locale: null
  widgets: {
    collections: CollectionsWidget
  }
  user: User
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number
  name: string
  roles: ('admin' | 'editor')[]
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  sessions?:
    | {
        id: string
        createdAt?: string | null
        expiresAt: string
      }[]
    | null
  password?: string | null
  collection: 'users'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: number
  name: string
  shortName: string
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null
  slug: string
  description: string
  websiteUrl: string
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educational-programs".
 */
export interface EducationalProgram {
  id: number
  title: string
  shortTitle: string
  /**
   * Формується автоматично з назви програми, рівня освіти та кодів спеціальності.
   */
  adminTitle?: string | null
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null
  slug: string
  /**
   * Новий код, наприклад F2.
   */
  specialtyCode: string
  /**
   * Старий код, наприклад 121.
   */
  legacySpecialtyCode: string
  specialtyName: string
  educationLevel: 'bachelor' | 'master'
  department: number | Department
  studyForms?:
    | {
        form: 'full-time' | 'part-time' | 'dual'
        durationLabel: string
        note?: string | null
        id?: string | null
      }[]
    | null
  isFeatured?: boolean | null
  sortOrder?: number | null
  description: string
  heroText: string
  tags?:
    | {
        label: string
        id?: string | null
      }[]
    | null
  careers?:
    | {
        title: string
        description: string
        id?: string | null
      }[]
    | null
  studyFocus?:
    | {
        title: string
        description: string
        id?: string | null
      }[]
    | null
  faq?:
    | {
        question: string
        answer: string
        id?: string | null
      }[]
    | null
  seoTitle?: string | null
  seoDescription?: string | null
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tuition-rates".
 */
export interface TuitionRate {
  id: number
  /**
   * Рівень освіти (бакалавр/магістр) береться з обраної освітньої програми.
   */
  educationalProgram: number | EducationalProgram
  academicYear: string
  studyForm: 'full-time' | 'part-time' | 'dual'
  availability: 'available' | 'unavailable' | 'to-be-announced'
  amountPerYear?: number | null
  totalAmount?: number | null
  currency: 'UAH'
  note?: string | null
  sortOrder?: number | null
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-documents".
 */
export interface ProgramDocument {
  id: number
  title: string
  /**
   * Обирай програму з потрібним рівнем освіти: бакалавр або магістр.
   */
  educationalProgram: number | EducationalProgram
  type:
    | 'educational-program'
    | 'previous-educational-program'
    | 'syllabus'
    | 'work-program'
    | 'curriculum'
    | 'accreditation'
    | 'review'
    | 'other'
  periodLabel?: string | null
  /**
   * Поки без Media/R2. Пізніше можна додати file relationship.
   */
  url: string
  description?: string | null
  sortOrder?: number | null
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number
  document?:
    | ({
        relationTo: 'users'
        value: number | User
      } | null)
    | ({
        relationTo: 'departments'
        value: number | Department
      } | null)
    | ({
        relationTo: 'educational-programs'
        value: number | EducationalProgram
      } | null)
    | ({
        relationTo: 'tuition-rates'
        value: number | TuitionRate
      } | null)
    | ({
        relationTo: 'program-documents'
        value: number | ProgramDocument
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: number | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number
  user: {
    relationTo: 'users'
    value: number | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T
  roles?: T
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
  sessions?:
    | T
    | {
        id?: T
        createdAt?: T
        expiresAt?: T
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  name?: T
  shortName?: T
  generateSlug?: T
  slug?: T
  description?: T
  websiteUrl?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educational-programs_select".
 */
export interface EducationalProgramsSelect<T extends boolean = true> {
  title?: T
  shortTitle?: T
  adminTitle?: T
  generateSlug?: T
  slug?: T
  specialtyCode?: T
  legacySpecialtyCode?: T
  specialtyName?: T
  educationLevel?: T
  department?: T
  studyForms?:
    | T
    | {
        form?: T
        durationLabel?: T
        note?: T
        id?: T
      }
  isFeatured?: T
  sortOrder?: T
  description?: T
  heroText?: T
  tags?:
    | T
    | {
        label?: T
        id?: T
      }
  careers?:
    | T
    | {
        title?: T
        description?: T
        id?: T
      }
  studyFocus?:
    | T
    | {
        title?: T
        description?: T
        id?: T
      }
  faq?:
    | T
    | {
        question?: T
        answer?: T
        id?: T
      }
  seoTitle?: T
  seoDescription?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tuition-rates_select".
 */
export interface TuitionRatesSelect<T extends boolean = true> {
  educationalProgram?: T
  academicYear?: T
  studyForm?: T
  availability?: T
  amountPerYear?: T
  totalAmount?: T
  currency?: T
  note?: T
  sortOrder?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-documents_select".
 */
export interface ProgramDocumentsSelect<T extends boolean = true> {
  title?: T
  educationalProgram?: T
  type?: T
  periodLabel?: T
  url?: T
  description?: T
  sortOrder?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown
  }
  width: 'full'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
